### ISSUE TITLE
hapi v17 support

### ISSUE THREAD

**Issue by travi** [mhazy/hapi-github-webhooks#5]
not a lot of activity here lately, but i suppose not much is needed for a fairly simple plugin. 

i've found it useful on some of my projects and would like to keep using it as i migrate them over hapi v17.

if i were to update the plugin to be compatible with hapi v17 would you accept the PR?

**Comment by mhazy** [comment]
@travi Thanks again for the PR, 2.0.0 has been pushed

**Comment by mhazy** [comment]
Oops, yeah. Converted things over and things are working again. Noticing an issue with `responseToolkit.continue` now though when run on 17.2 -- can dig into it later today and push up a PR.

Tossed a deprecation on 2.0.0

![image](https://user-images.githubusercontent.com/1699370/36258923-79dcc022-122a-11e8-88e3-245a52d522bc.png)

**Comment by travi** [comment]
> Tossed a deprecation on 2.0.0

Good call. 

Sorry i didnt catch it in my initial PR. normally i use [`rimraf`](https://github.com/isaacs/rimraf) to clean out build directories before generating the new assets, but I didn't go that far with this. Had I done so, I would have noticed this issue.

Let me know if there is anything you need from me to finish things up. I'm happy to test again once you have another release ready if you dont need anything before that.

**Comment by travi** [comment]
any further progress with this? need any help from me to get it over the finish line?

**Comment by travi** [comment]
what are your thoughts on this. do you want me to take another stab at getting this working. if you're interested in having an additional maintainer on the project, i'd be open to discussing options to help out.

**Comment by mhazy** [comment]
@travi -- I re-arranged things awhile ago but it fell off, can you take a look at the following branch and see if that'll work out? Would be good to be able to have tests for specific versions of hapi

https://github.com/mhazy/hapi-github-webhooks/tree/feature/es-modules

**Comment by travi** [comment]
sorry for the delayed response. finally getting a chance to take a look again, so hopefully ill have some updates to send your way somewhat soon.
